### PR TITLE
Compose: add Shibboleth and SSL for NextCloud

### PR DESCRIPTION
**Pull request by lower29**
This pull request addresses [RDSSARK-140](https://jiscdev.atlassian.net/browse/RDSSARK-140) by adding Shibboleth and SSL functionality to the NextCloud service. This builds on the work done in https://github.com/JiscRDSS/rdss-arkivum-nextcloud/pull/19.

The Shibboleth-enabled NextCloud service is part of the `am-shib` Compose config, and the NextCloud service has been moved from its own `docker-compose.nextcloud.yml` into the main `qa` config (with the build path in the `dev` config). I've done what I can to preserve what was in the old NextCloud readme by merging it into the Archivematica-focused dev readme.

NextCloud acts as its own SP, so doesn't use the SP proxy that Archivematica does. The IdP's configuration has been updated to include NextCloud in its list of service providers. The same `nginx-ssl` proxy is used to provide the SSL layer for NextCloud, so that it is able to run on port 443 like the dashboard and storage service. By default it is available at https://nextcloud.example.ac.uk/ but this is configurable in the usual way using environment variables.

The Ansible playbook has been updated to use the latest shibboleth-enabled NextCloud image. Once this has been formally released and we have a semver tag, we should use that instead of the specific branch.

### CODE REVIEW

**Comment by mamedin** [comment]
Hi Richard, I have not finished yet the deploy and upgrade tests. I can tell you what I have already seen:

a) The deploy.sh shows this outdated info when deploying (at the beginning and the end):
```
NextCloud:                     http://DOMAIN:8888/
```
b) I have found some issues related to the `REGISTRY` variable. I have created a clone of this branch and added two small fixes here: `dev/nextcloud-shibboleth-mamedin`

c) At this moment I'm finding this error when running deploy.sh with `dev/nextcloud-shibboleth-mamedin`:

```
Creating rdss_archivematica-mcp-server_1      ... done
Creating rdss_archivematica-dashboard_1       ... done
Creating rdss_archivematica-mcp-client_1                     ... done
Creating rdss_nginx-ssl_1                                    ... done
Creating rdss_archivematica-automation-tools_1               ... done
Creating rdss_rdss-archivematica-channel-adapter-publisher_1 ... done
Creating rdss_rdss-archivematica-channel-adapter-consumer_1  ... done
make -C qa bootstrap ;  make -C am-shib bootstrap ;  make -C shib-local bootstrap ;
make[1]: Entering directory '/home/ubuntu/src/rdss-archivematica/compose/qa'
# Specify compose file explicitly, we don't want to build any other container sets
COMPOSE_FILE=/home/ubuntu/src/rdss-archivematica/compose/docker-compose.qa.yml docker-compose build
minio uses an image, skipping
dynalite uses an image, skipping
redis uses an image, skipping
gearmand uses an image, skipping
nginx uses an image, skipping
elasticsearch uses an image, skipping
minikine uses an image, skipping
mysql uses an image, skipping
archivematica-mcp-server uses an image, skipping
fits uses an image, skipping
rdss-archivematica-msgcreator uses an image, skipping
# Make sure NextCloud apps are built
make[2]: Entering directory '/home/ubuntu/src/rdss-archivematica/src/rdss-arkivum-nextcloud'
# Build the 'files_mv' NextCloud app
# Build the 'user_saml' NextCloud app
make[2]: Leaving directory '/home/ubuntu/src/rdss-archivematica/src/rdss-arkivum-nextcloud'
# Wait for MySQL to be ready
clamavd uses an image, skipping
archivematica-storage-service uses an image, skipping
archivematica-dashboard uses an image, skipping
rdss-archivematica-channel-adapter-consumer uses an image, skipping
archivematica-automation-tools uses an image, skipping
rdss-archivematica-channel-adapter-publisher uses an image, skipping
archivematica-mcp-client uses an image, skipping
nextcloud uses an image, skipping
Waiting for mysql to be ready...
Waiting for mysql to be ready...
Waiting for mysql to be ready...
Waiting for mysql to be ready...
Waiting for mysql to be ready...
Waiting for mysql to be ready...
```

**Comment by lower29** [comment]
Thanks @mamedin, I always forget about the deployment script when I make changes to compose!

The changes you've made on `dev/nextcloud-shibboleth-mamedin` make sense; I'll add them to the branch for this PR.

The problem with `waiting for mysql to be ready...` is actually something to do with a recent change to docker-compose. Matthew and I identified it a few days ago, but I haven't had chance to properly investigate or address it. I'll raise an issue for it.

**Comment by lower29** [comment]
Hi @mamedin I've now included the deployment fixes into the commits for this PR. The changes for the shib-sp-proxy image in the compose config are now in #193. The docker-compose problem has been merged from PR #192. Are we ready to merge this now?

**Comment by lower29** [comment]
Further testing with @mamedin has highlighted a couple of other changes that are required, so I've updated this PR with those. It's just some small changes to the `nextcloud` service configuration, adding some environment variable overrides etc.

**Pull request merged**
